name: flutter_incall_manager
description: Flutter InCall Manager plugin for iOS/Android.
version: 0.1.0
homepage: https://github.com/kangshaojun/flutter-incall-manager

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.flutterincallmanager
        pluginClass: FlutterIncallManagerPlugin
      ios:
        pluginClass: FlutterIncallManagerPlugin
